name: Lingo-PR
description: Summarise PR diff and translate
inputs:               # ← أضف هذا
  patch:
    description: "Git diff text"
    required: true
runs:
  using: node20
  main: dist/index.js
branding:
  icon: message-square
  color: blue
